"""Data models for Report Aggregation Agent.

AggregatedReport is the final unified output consumed by
integrations layer for PR comments, callback events, and storage.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ReportSummary(BaseModel):
    """Top-level summary for quick consumption."""

    blocking_count: int = Field(default=0, description="Number of blocking findings")
    warning_count: int = Field(default=0, description="Number of warnings/suggestions")
    pass_count: int = Field(default=0, description="Number of checks passed")
    security_scan_duration_ms: int = Field(default=0)
    migration_scan_duration_ms: int = Field(default=0)


class AggregatedReport(BaseModel):
    """Unified output from all analysis chains.

    This is the canonical output that feeds:
    - PR comment (Markdown, security-first)
    - Full report file (JSON/HTML)
    - Webhook callback events
    - Web dashboard

    INVARIANT: This model NEVER modifies upstream business conclusions.
    It only merges, deduplicates, sorts, and formats.
    """

    scan_id: str = Field(..., description="Associated scan ID")
    repo_url: str = Field(default="", description="Repository URL")
    commit_sha: str = Field(default="", description="HEAD commit SHA")
    scan_scope: str = Field(default="full", description="full | diff")
    generated_at: str = Field(default="", description="UTC ISO 8601")
    summary: ReportSummary = Field(default_factory=ReportSummary)

    # Upstream results (passed through without modification)
    security: dict | None = Field(
        default=None, description="FinalSecurityDecision from Conflict Agent (unmodified)"
    )
    migration: dict | None = Field(
        default=None, description="MigrationReport from Migration Agent (unmodified)"
    )

    # Output artifacts (generated by this agent)
    pr_comment_markdown: str = Field(
        default="", description="Rendered PR comment (Markdown)"
    )
    full_report_url: str | None = Field(
        None, description="URL or path to the full HTML/JSON report"
    )

    # Metadata
    degraded: bool = Field(
        default=False, description="True if any upstream result was degraded"
    )
    degraded_reasons: list[str] = Field(
        default_factory=list, description="Aggregated degradation reasons"
    )
    appeal_count: int = Field(default=0, description="Number of appealable findings")
    human_intervention_required: bool = Field(
        default=False, description="Passed through from conflict agent"
    )
